# https://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/

apiVersion: v1
kind: Service
metadata:
  name: front-service
  annotations:
    networking.gke.io/managed-certificates: "front-lb-ssl-cert"

# https://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/#ServiceSpec
spec:
  type: LoadBalancer
  selector:
    name: front-pod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80