apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: back-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8"
spec:
  ingressClassName: nginx
  # tls:
  # - hosts:
  #   - nginx-ingress.nginx-ingress.svc.cluster.local
  #   secretName: tls-back-secrets
  rules:
  - host: back-service.default.svc.cluster.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: back-service
            port:
              number: 6060