apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: example-issuer
spec:
  acme:
    email: facundolaffont@gmail.com
    # server: https://acme-staging-v02.api.letsencrypt.org/directory # API para test.
    server: https://acme-v02.api.letsencrypt.org/directory # API para producción.
    privateKeySecretRef:
      name: example-issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token